const express = require('express');
const path = require('path');
const helmet = require('helmet');
const morgan = require('morgan');
const { ensureDataFiles, readJson } = require('./utils/storage');
const { games, categories } = require('./utils/games');
ensureDataFiles();
const app = express();
app.use(helmet({ contentSecurityPolicy: false }));
app.use(morgan('dev'));
app.use(express.json({ limit: '1mb' }));
app.use(express.static(path.join(__dirname, 'public'), { maxAge: '1h' }));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/games', require('./routes/games'));
app.use('/api/scores', require('./routes/scores'));
app.use('/api/admin', require('./routes/admin'));
app.get('/api/stats', (req,res)=>{ const users=readJson('users.json'), scores=readJson('scores.json'), stats=readJson('gameStats.json'); const popular=Object.entries(stats.gamePlays||{}).sort((a,b)=>b[1]-a[1])[0]?.[0]||'None'; res.json({ totalUsers:users.length,totalGames:games.length,totalGamesPlayed:scores.length,totalScoresSubmitted:scores.length,mostPopularGame:popular,dailyActiveUsers:Object.fromEntries(Object.entries(stats.dailyActiveUsers||{}).map(([d,u])=>[d,u.length])), categories }); });
app.get('*', (req,res)=>res.sendFile(path.join(__dirname, 'public', 'index.html')));
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`GameVerse running on http://localhost:${PORT}`));
module.exports = app;
