const express = require('express');
const { games, categories } = require('../utils/games');
const { readJson, updateJson } = require('../utils/storage');
const router = express.Router();
function visibleStudioGames(req) { const username = String(req.headers['x-username'] || '').trim(); const users = readJson('users.json'); const requester = users.find(u => u.username === username); return readJson('studioGames.json').filter(g => g.visibility !== 'private' || g.username === username || requester?.isAdmin || username === 'ojasthescientist'); }
function allGames(req) { return [...visibleStudioGames(req).map(g => ({ ...g, category: 'Player Studio', tags: ['Player Studio', g.type, 'Community', g.visibility || 'public'], multiplayer: g.type === 'multiplayer', instructions: 'This is a Player Studio game. It runs in a sandboxed HTML/CSS/JavaScript iframe.', featured: false, trending: false, isNew: true, controlType: 'tap' })), ...games]; }
router.get('/', (req, res) => { const q = (req.query.q || '').toLowerCase(); const list = allGames(req); res.json({ games: q ? list.filter(g => [g.name,g.category,...(g.tags||[])].join(' ').toLowerCase().includes(q)) : list, categories: ['Player Studio', ...categories] }); });
router.get('/:id', (req, res) => { const game = allGames(req).find(g => g.id === req.params.id); game ? res.json({ game }) : res.status(404).json({ error: 'Game not found' }); });
router.get('/:id/comments', (req, res) => { const comments = readJson('gameStats.json').comments?.[req.params.id] || []; res.json({ comments }); });
router.post('/:id/rate', async (req, res) => { const rating = Number(req.body.rating); if (rating < 1 || rating > 5) return res.status(400).json({ error: 'Rating must be 1-5' }); await updateJson('gameStats.json', s => { s.ratings[req.params.id] = [...(s.ratings[req.params.id] || []), { username: req.body.username || 'Guest', rating, date: new Date().toISOString() }]; return s; }); res.json({ ok: true }); });
router.post('/:id/comments', async (req, res) => { const text = String(req.body.text || '').trim().slice(0, 300); if (!text) return res.status(400).json({ error: 'Comment required' }); await updateJson('gameStats.json', s => { s.comments[req.params.id] = [...(s.comments[req.params.id] || []), { username: req.body.username || 'Guest', text, date: new Date().toISOString() }]; return s; }); res.json({ ok: true }); });
module.exports = router;
